### ISSUE TITLE
LUA error when moving items into Bagnon bank from bags

### ISSUE THREAD

**Issue by raysmith59** [teelolws/DataStore_Containers#1]
I was moving some BoE items from my bags to my bank via right-click, after a dozen or so I started getting this every time I moved another one:

5x DataStore_Containers\DataStore_Containers-9.0.1-027.lua:422: attempt to index local 'refDB' (a nil value)
[string "@DataStore_Containers\DataStore_Containers-9.0.1-027.lua"]:422: in function <DataStore_Containers\DataStore_Containers.lua:344>
[string "@DataStore_Containers\DataStore_Containers-9.0.1-027.lua"]:599: in function <DataStore_Containers\DataStore_Containers.lua:594>
[string "=[C]"]: ?
[string "@Accountant\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ant\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Accountant\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by teelolws** [comment]
Eh. Lazy fix time: https://github.com/teelolws/DataStore_Containers/commit/dbdd487cfe21400269afd962289dffff79bc4772
